# Neural Network Classifier
Using the neural network MLP classifier from scikit to create a two-dimensional linear classifier for 3 classes

In [42]:
import csv

X = []
Y = []

with open('spiral.csv') as csv_file:
    csv_reader = csv.reader(csv_file, delimiter=',')
    line_count = 0
    for row in csv_reader:
        if line_count != 0:
            X.append([float(row[0]), float(row[1])])
            Y.append(int(row[2]))
        line_count+=1

In [43]:
import numpy as np
from sklearn import neural_network

# Build the MLP Classifier
X = np.array(X)
Y = np.array(Y)
clf = neural_network.MLPClassifier(hidden_layer_sizes=(100, 72), max_iter=1000, tol=1e-3)
clf.fit(X, Y)

print(clf.predict([[0.115,0.554]])) # -> 0.115,0.554,1
print(clf.predict([[0.042,0.092]])) # -> 0.042,0.092,0
print(clf.predict([[-0.762,0.373]])) # -> -0.762,0.373,2
print(clf.predict([[-0.250,0.189]])) # -> -0.250,0.189,1

[1]
[0]
[2]
[1]


## Confusion Matrix

Using TP + TN etc. for accuracy score

In [73]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
import random

# Get confusion matrix
y_res = []
x_pred = []

for i in range(8):
    ri = random.choice(np.arange(Y.size))
    y_res.append(Y[ri])
    x_pred.append(X[ri])

y_true = np.array(y_res)
y_pred = clf.predict(x_pred)

print(f'y_true: {y_true}')
print(f'y_pred: {y_pred}')

print('\nConfusion Matrix (y_true, y_pred):')
print(confusion_matrix(y_true, y_pred))

print('\nAccuracy Score:')
print(accuracy_score(y_true, y_pred))


y_true: [1 1 1 2 0 1 1 1]
y_pred: [1 1 1 2 0 1 1 1]

Confusion Matrix (y_true, y_pred):
[[1 0 0]
 [0 6 0]
 [0 0 1]]

Accuracy Score:
1.0


We can interpret this using the 1-class:


+-----------+--------------+-----------+
|Num of 1's |    True 1    | True not 1|
+===========+==============+===========+
|  Pred 1   |     TP=6     |    FP=0   |
+-----------+--------------+-----------+
| Pred not 1|     FN=0     |    TN=2   |
+-----------+--------------+-----------+

Accuracy Score:

\begin{equation*}
ACC = \frac{TP + TN}{TP + TN + FP + FN}
\end{equation*}

\begin{equation*}
ACC = \frac{6 + 2}{6 + 2 + 0 + 0} = \frac{8}{8} = 1
\end{equation*}